### ISSUE TITLE
Expose option to skip beautification

### ISSUE THREAD

**Issue by THEjoezack** [rejas/gulp-json-editor#10]
I would like to be able to bypass the beautification process. I can see there's an existing variable that can be used, but it's hard-coded.

I would like this exposed as one of the beautification options.

I'll go ahead and submit a PR, unless I'm missing something.

**Comment by ribeirobreno** [comment]
#11 is what i was looking for. Merging would be very appreciated.

**Comment by rejas** [comment]
Closed via https://github.com/rejas/gulp-json-editor/pull/11
