### ISSUE TITLE
Out of date js-beautify

### ISSUE THREAD

**Issue by hexus** [rejas/gulp-json-editor#14]
The `js-beautify` is out of date and prevents me from using the `'brace-style': 'collapse-preserve-inline'` option, which was fixed for Node in [1.6.2](https://github.com/beautify-web/js-beautify/blob/v1.6.2/CHANGELOG.md).

Right now I'm trying to use `npm shrinkwrap` to work around this, which is a pain. Would be great just to see it updated. :smile:

**Comment by rejas** [comment]
Closed by https://github.com/rejas/gulp-json-editor/commit/4954177e44c309483fd884d5f73a102d679df735

**Comment by hexus** [comment]
:raised_hands: No way! I reported this nearly two years ago, thank you!
