### ISSUE TITLE
NPM ownership

### ISSUE THREAD

**Issue by rejas** [rejas/gulp-json-editor#17]
Hi @morou 
could you also transfer the ownership of this library in the npm registry to me? Otherwise I cannot release a new version :-(
Cheers and Thanks for all your work

**Comment by morou** [comment]
sure. please wait!

**Comment by morou** [comment]
I added you as owner of this package. Please check it. If you are able to publish this package, I'll remove myself as owner.

```sh
$ npm owner add rejas gulp-json-editor
+ rejas (gulp-json-editor)
$ npm owner ls gulp-json-editor       
rejas <npm@veeck.de>
morou <kazuhiro.nakae@gmail.com>
```

**Comment by rejas** [comment]
It worked, 2.2.2 is published.
