### ISSUE TITLE
outdated buffer in node 8+

### ISSUE THREAD

**Issue by jjhesk** [rejas/gulp-json-editor#19]
https://github.com/rejas/gulp-json-editor/blob/master/index.js#L71
https://nodejs.org/docs/latest-v9.x/api/buffer.html#buffer_class_method_buffer_allocunsafe_size
does it support higher version?

**Comment by rejas** [comment]
Hi @jjhesk sorry for the late answer. Yes, even the current version should run under node 10. But thanks for the hint, I will update the code accordingly soon

**Comment by rejas** [comment]
Fixed in v2.4.0
