### ISSUE TITLE
Add option to insert empty object

### ISSUE THREAD

**Issue by kimblim** [rejas/gulp-json-editor#29]
Hey,

I might be stupid here, but is it not possible to delete the contents of an object, ie. I am trying to delete all `dependencies` and `devDependencies` from a `package.json` file, like this:

```
return gulp
    .src('package.json')
    .pipe(jsonEditor({
      'dependencies': {},
      'devDependencies': {}
    }))
    .pipe(gulp.dest(destination))
```
However, that doesn't seem to work. Any other way of emptying those objects using this gulp package?

Thanx in advance!

**Comment by rejas** [comment]
Yes, its possible:
```
return gulp
    .src('package.json')
    .pipe(jsonEditor(function(obj) {
        obj.dependencies = {};
        obj.devDependencies = {};
        return obj;
    }))
    .pipe(gulp.dest(destination))

```

**Comment by kimblim** [comment]
Works, thanx a lot!
