### ISSUE TITLE
Merging JSON docs?

### ISSUE THREAD

**Issue by robertdunaway** [rejas/gulp-json-editor#8]
Would it be possible to take 2 or 3 JSON objects and merge them into one without duplicates?

I have 3 apps that each have their own menu configured in JSON.  They each have menu items inside the same categories so each JSON will have Category1 and so on.  I'd like to merge these JSON files together at build time so that at run time the menu doesn't care where the JSON comes from.  It just builds the menu.

Is this kind of thing possible with gulp-json-editor?

Thanks,
Bob

**Comment by rejas** [comment]
Hi Bob, you can take a look at [gulp-merge-json](https://github.com/joshswan/gulp-merge-json) for this functionality
